### ISSUE TITLE
Bad Log Output on first Startup

### ISSUE THREAD

**Issue by dkleber89** [dkleber89/ioBroker.beckhoff#1]
Bad Startup Log ... But after that Adapter works properly. 

Log Output after first Startup:

Source|Time|Level|Message
-- | -- | -- | --
beckhoff.0 | 2018-11-03 21:18:38.498 | error | at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
beckhoff.0 | 2018-11-03 21:18:38.498 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
beckhoff.0 | 2018-11-03 21:18:38.498 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
beckhoff.0 | 2018-11-03 21:18:38.498 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
beckhoff.0 | 2018-11-03 21:18:38.498 | error | at Socket.onevent (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:278:10)
beckhoff.0 | 2018-11-03 21:18:38.498 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
beckhoff.0 | 2018-11-03 21:18:38.498 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
beckhoff.0 | 2018-11-03 21:18:38.498 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3425:37)
beckhoff.0 | 2018-11-03 21:18:38.498 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.beckhoff/beckhoff.js:95:25)
beckhoff.0 | 2018-11-03 21:18:38.498 | error | at Object.module.exports [as workerPlcToAdapter] (/opt/iobroker/node_modules/iobroker.beckhoff/lib/workerPlcToAdapter.js:42:9)
beckhoff.0 | 2018-11-03 21:18:38.498 | error | TypeError: Cannot read property 'on' of null
beckhoff.0 | 2018-11-03 21:18:38.482 | error | message beckhoff.0.info.connection [object Object] Cannot read property 'on' of null
beckhoff.0 | 2018-11-03 21:18:38.487 | error | at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
beckhoff.0 | 2018-11-03 21:18:38.487 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
beckhoff.0 | 2018-11-03 21:18:38.487 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
beckhoff.0 | 2018-11-03 21:18:38.487 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
beckhoff.0 | 2018-11-03 21:18:38.487 | error | at Socket.onevent (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:278:10)
beckhoff.0 | 2018-11-03 21:18:38.487 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
beckhoff.0 | 2018-11-03 21:18:38.487 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
beckhoff.0 | 2018-11-03 21:18:38.487 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3425:37)
beckhoff.0 | 2018-11-03 21:18:38.487 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.beckhoff/beckhoff.js:95:25)
beckhoff.0 | 2018-11-03 21:18:38.487 | error | at Object.module.exports [as workerPlcToAdapter] (/opt/iobroker/node_modules/iobroker.beckhoff/lib/workerPlcToAdapter.js:42:9)
beckhoff.0 | 2018-11-03 21:18:38.487 | error | TypeError: Cannot read property 'on' of null
beckhoff.0 | 2018-11-03 21:18:38.482 | error | message beckhoff.0.info.connection [object Object] Cannot read property 'on' of null
beckhoff.0 | 2018-11-03 21:18:38.455 | info | Connected to PLC. State of PLC: RUN
beckhoff.0 | 2018-11-03 21:18:38.426 | info | starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.beckhoff, node: v6.14.4

**Comment by dkleber89** [comment]
Make some changes so the Problem with the Connection should be done ... But i see on my Testsystem (Windows Machine) the Process ending working fine ... On my other System (linux / docker) processes are not ending and so there are big troubles and Adapter wont work on this Machines ... Don´t know wy :-(

**Comment by dkleber89** [comment]
On Adapter Unload the Callbacks are not called so this was the Problem of the not ended Processes ... But there are still Problems with not ended Processes when Adapter run and Loglevel will changed ...
